### ISSUE TITLE
About rebirth after reaching the goal

### ISSUE THREAD

**Issue by huyongf** [csofranz/DML#3]
Dear Friends.
In the process of learning to use DML, I ran into a problem when using the feature of respawn after reaching the target, that is, I created two trigger areas, group A is in trigger area #1 as the starting point and arrives inside trigger area #2 as the end point, but I can never get group A to respawn from the new back to trigger area #1. Please help me solve the problem! If it's best, I'll attach a column so that I can learn this function better, thanks in advance.

**Comment by csofranz** [comment]
Can you share the mission so I can have a look? 

Perhaps also take a look at the 'forever looping spawns' demo (and documentation) that should do exactly what you seem to be trying

**Comment by huyongf** [comment]
I watched the demo of "Forever Loop Generation", and I found a bug that when using timed respawn, the respawn target cannot have static objects, otherwise there will be two identical respawns. For example, if we reborn an aircraft carrier at regular intervals, if there are static objects on the carrier, the carrier will become 2 identical reborn bodies when it is reborn, and even the carrier's carrier aircraft will not work properly.

**Comment by huyongf** [comment]
I have an idea that it is possible to do respawn by number of times, for example, I activate a group through the radio menu, and after this group dies 5 times, activate this group again through the radio menu. This mode is very helpful for newcomers to practice.

**Comment by csofranz** [comment]
> the respawn target cannot have static objects, otherwise there will be two identical respawns

With carriers, multiple clones at the same time can become an issue, yes. I'll investigate if this is because the linked objects are screwed up, or this is a bug in DML

>I have an idea that it is possible to do respawn by number of times, for example, I activate a group through the radio menu, and after this group dies 5 times, activate this group again through the radio menu.

There are many interesting and fun ways to do this. I recommend you also look into randomizing templates, so the spawns are different each time and make the mission more unpredictable. Perhaps look at the 'Attack of the CloneZ' mission and documentation that randomizes SAM sites each time a cloner is activated.

**Comment by huyongf** [comment]
Thank you very much my friend, the problem of reaching the target respawn has been solved, now there is a new problem, that is, the problem of group refresh after capturing a base, I did not find the relevant case in the demo you provided, although it can be done with ME, but ME can only be used once, after being captured again it will not work. Please help me solve this problem, thank you very much!

**Comment by csofranz** [comment]
I'm sure we can get this resolved quickly. What is it that you want to achieve, what have you tried, and what is still missing?

**Comment by huyongf** [comment]
I followed the ME's spawning mission you provided and changed the mission to one where both sides capture the airport, and the red side automatically becomes ground and air defense troops after capture, and the blue side also generates ground and air defense troops after capture, using the ME's flag markers to control, but only once, not infinitely. I want them to automatically generate air defense and ground troops infinitely according to the owner of the airfield, regardless of whether the red or blue side automatically generates them after capturing the airfield, instead of only once.

**Comment by csofranz** [comment]
> I want them to automatically generate air defense and ground troops infinitely according to the owner of the airfield

That should not be too difficult. If you are using Capturable Zones, the defenders only reproduce when they are destroyed, attackers produce regularly. If you are using FARP zones, I believe the default behavior is only once. Is that the issue that you are having (my apologies, but your descriptions are a bit too brief to fully understand what the issue may be :) ) 
So, to establish what you are trying to do: You want an airfield or FARP that continually produces troops for the side that holds the airfield? You currently are using FARP Zone modules which only produce defenders once. 
You would prefer it if the FARP/Airfield continually produces ground forces but the FARP Zone doesn't do that.

Is that a correct assessment of what you are trying to accomplish and the issue you are facing?

If so, imagine the FARP/Airfield does automatically spawn defenders - when should that happen, and what should be spawned? 

I think we'll find a way to make this work :)

**Comment by huyongf** [comment]
I pay on the task I changed according to ME's spawn, you help me see, the problem is 2 points.
1, the red side captures the airport once after generating ground troops and anti-aircraft units. When captured by the blue side again after the capture of this airport will not automatically generate ground troops and anti-aircraft units.
2, I want to generate the specified troops in a specific area according to the flag markers generated after the capture of the airport on eithe

**Comment by huyongf** [comment]
[Uploading Automatic capture generation.zip…]()

**Comment by huyongf** [comment]
You should be able to understand what I think when you look at this chart

**Comment by huyongf** [comment]
I now regularize my questions! I hope you help me to solve the problem
1, use the flag to generate a new group, this is of course using DML, not ME, and this group is not activated at the beginning of the task. I've tried cloning but no way to finish. I also tried to generate this group in a mode like radio call (cloner, clone?), but it also did not work.
2, about base capture, automatic generation of defense system, this should be able to set the number of times. This can be done without the capture module, but directly using the flag, but in the DML, I tried many times can not be completed.

Of course all these can be done using ME, but this loses the meaning of using DML. What I need help with now is that you give me a direction to learn

**Comment by csofranz** [comment]
OK, I'm not entirely sure if I understood you correctly, but I think I may have an approach that could work.
Use a baseCaptured module. This module sends signals when the nearest airfield or FARP is captured, and also always provides a signal on the baseOwner output.
Each base has blue and red cloners. They only spawn when their side owns the zone. How do we do that? By using a two changers per cloner as a controller and gate. The "red changer" only transmits a clone impulse when the owner of the base is red (red controller: baseOwner=1 --> 1 which opens red gate) and the "blue changer" only transmits a clone impulse when the owner of the base is blue  
That way you can easily clone blue groups when blue owns the farp, and red groups when red owns the farp.

I'll see if I have the time to come up with a demo mission for you to look at in the next few days 
We can use the baseOwner to control

**Comment by huyongf** [comment]
I think I understand the properties of the trigger zone in general, but I don't want to use the radio, so can I use a flag to automatically clone a hidden target. I've tried repeatedly and read the documentation. Still can't solve this

**Comment by huyongf** [comment]
I also saw the demo you provided, doors and switches, and I've been working on this module for the past two days, but it feels like it's just almost something. First of all, this module is great for making tasks more personalized. It's better to solve one problem at a time, too many are easily mixed together

**Comment by csofranz** [comment]
My apologies, but I'm German, and I have great difficulties understanding what you are saying. 

In any event, I've completed a nice demo mission that clones red or blue troops depending on who owns the farp, and re-spawns 10 seconds after a kill

Perhaps look at the demo that I have included below, and maybe it helps
[farp cap w spawns.zip](https://github.com/csofranz/DML/files/9104793/farp.cap.w.spawns.zip)

**Comment by huyongf** [comment]
Ich habe auch die von Ihnen zur Verfügung gestellte Demo gesehen, Türen und Schalter, und ich habe in den letzten zwei Tagen an diesem Modul gearbeitet, aber ich habe das Gefühl, dass mir einfach etwas fehlt. Zunächst einmal ist dieses Modul großartig, um Aufgaben persönlicher zu gestalten. Es ist besser, ein Problem nach dem anderen anzugehen, zu viele können leicht durcheinander geraten.

**Comment by huyongf** [comment]
Vielen Dank, ich habe mir die von Ihnen zur Verfügung gestellte Demo zu "Doors and Switches" angesehen und ich glaube, ich verstehe die Eigenschaften der Triggerzone im Allgemeinen, aber ich möchte das Funkgerät nicht verwenden, also kann ich ein Flag verwenden, um automatisch ein verstecktes Ziel zu klonen. Ich habe es wiederholt versucht und die Dokumentation gelesen. Kann das Problem immer noch nicht lösen

**Comment by huyongf** [comment]
Vielen Dank für die Demo, mit Ihrer Hilfe wurde mein Problem gelöst, jetzt ist das einzige Problem, dass ich "OUT!" bei der Ausgabe der Flagge und "F?" beim Empfang verwende, es löst einfach nicht aus, sehr verwirrend! Ich hoffe, Sie können mir eine Antwort geben!

**Comment by csofranz** [comment]
Be careful when using generic input names like f? and out!. I recommend that you look up each module in the Quick Reference, and use the module-specific input and output names to avoid confusion.

Also, use the brand new debugger (simply use the debug? attribute and list the flag names that you are interested in) to help you observe the flags that you are interested in. The demo I included already has the debugger installed, perhaps look at the new documentation that came with today's release for more info.

**Comment by huyongf** [comment]
Vielen Dank, das Problem ist gelöst. Ein Problem, das ich bei der Nutzung des Radios gefunden habe, ist, dass man das Radiomenü nur aktivieren kann, wenn man ein bestimmtes Gebiet erreicht, ansonsten gibt es ein Zeitlimit, aber es ist immer noch nicht so bequem wie das Erreichen eines bestimmten Gebiets und das Aktivieren des Radios.

**Comment by huyongf** [comment]
Mein Freund, wie kopiert man bei der Basiserfassung die Flugzeugslots eines Spielers, der sie bereits eingerichtet hat, z.B. indem man das Modell des Geburtsflughafens auf den eroberten Flughafen kopiert, nachdem man einen Flughafen erobert hat?

**Comment by csofranz** [comment]
> Ein Problem, das ich bei der Nutzung des Radios gefunden habe, ist, dass man das Radiomenü nur aktivieren kann, wenn man ein bestimmtes Gebiet erreicht, ansonsten gibt es ein Zeitlimit

There must have been a lot lost in translation there. Are you looking for a way to trigger showing the menu and remove it later? If so, I've completed removing the menu on trigger, and will later add the ability to only show a menu when you trigger it :)

**Comment by csofranz** [comment]
>kopiert man bei der Basiserfassung die Flugzeugslots eines Spielers, der sie bereits eingerichtet hat, z.B. indem man das Modell des Geburtsflughafens auf den eroberten Flughafen kopiert, nachdem man einen Flughafen erobert hat?

(I recommend you use English Auto Translation, the German translations are even harder to read that English)

You need to copy paste the original player plane to the desired slot on the enemy airfield. Manually set the airfield's coalition, and if you have SSB and SSBclient running the slots are automatically blocked for the enemy airfield.

**Comment by csofranz** [comment]
OK, I've updated radioMenus to support adding and removing a menu at will, controlled by flags. This should enable you to show a menu only when in a zone.

The next release is slated for coming Thursday, by that time I plan to also have the documentation updated accordingly

**Comment by huyongf** [comment]
Is there a possibility to modify the properties of the area in specific areas, such as: unlimited fuel, unlimited ammunition, so as to better expand the playability of the mission

**Comment by csofranz** [comment]
>modify the properties of the area in specific areas, such as: unlimited fuel, unlimited ammunition

No, those are mission-global settings that currently can't be changed by scripts.

**Comment by huyongf** [comment]
This is more limited, there is another is when the player first obtains the aircraft when playing audio or text? Can this be done, I tried many ways, only all messages, or camp messages, can not be assigned to individuals

**Comment by csofranz** [comment]
The ability to send messages to individual units was added to DCS a few weeks ago. I have not yet added it to DML, currently it only offers message to all and to coalition. Group and Unit will follow later

**Comment by huyongf** [comment]
My friend, do you plan to develop a combat score system, so that it will be more fun to use DML to plan mission drop

**Comment by csofranz** [comment]
> do you plan to develop a combat score system

So you don't like the PlayerScore module?  :) 

What kind of score are you looking for ?

**Comment by huyongf** [comment]
My idea is to gain points through fighting, and through the points, you can buy planes, or arm these on the ground, or buy rebirth positions in the occupied airport.

**Comment by csofranz** [comment]
>  through the points, you can buy planes, or arm these on the ground, or buy rebirth positions in the occupied airport.

Ah, well, that's an entire _business model_.  :) I had an initial design for this ('factory zones' that you have to capture that generate income, and then you'd be able to spend for other things), but it was too complex to fit into DML. 
Perhaps some time later, when DML has matured enough for big plug-ins like that I can revisit the idea.

**Comment by huyongf** [comment]
Actually, I think it shouldn't be so troublesome. You mean to occupy an area to make him generate income, while my idea is to generate income through the mode of fighting. This is more intuitive, and after earning income, I will spend it in other occupied places.

**Comment by csofranz** [comment]
> while my idea is to generate income through the mode of fighting

The problem isn't so much generation of income (indeed, kills, rescues, occupation, anything goes) but the _spending_ of it: how would you attribute your income to units, and how would that control cloners/spawners. In other words: how can this work easily within DML's model of modules controlled by flags. We need a simple, easy way to something like this up with a few attributes and flags. That is the challenge. It's definitely possible to do that in Lua, but I don't see an easy way to translate that into DML.

I'll look into it at a later point in time, and if you have an idea, I'll of course be happy to look at that as well.

**Comment by huyongf** [comment]
True, but LUA's words are slow to use, and it's hard to understand some of the DML's needs. It's very troublesome to get LUA, so I hope you can develop this function.

**Comment by huyongf** [comment]
What is the main update?

**Comment by csofranz** [comment]
Persistence - being able to save and load a mission

You may find this page of interest: https://forum.dcs.world/topic/290975-dml-mission-creation-toolbox-no-lua-required/?do=findComment&comment=5016896

**Comment by huyongf** [comment]
There is still no message sending function for players in this update.

**Comment by csofranz** [comment]
Yes, thank you. I believe I already mentioned that group and unit messaging will come later. I have not date for that.

**Comment by huyongf** [comment]
Also, after the camp acquires the base, the player client is generated, which will increase the playability of the task.

**Comment by csofranz** [comment]
> after the camp acquires the base, the player client is generated

?

If possible, please use more words to describe your idea - the automatic translation is really difficult to understand for me. If you describe your idea in greater detail, I may be able to better understand what you are looking for. 

I believe with "camp" you mean "coalition", and with "base" you mean "FARP" or "Airfield". With "The player client is generated" I think you mean "a player can start from there". This is a feature that is available with SSBclient in DML, and requires that you install SSB and play as Multiplayer (even in single-player).

Please open a separate thread for these items so that other people who are looking for the same thing may find it.

**Comment by huyongf** [comment]
After obtaining the base, change the player's birth point to the current base.

**Comment by huyongf** [comment]
&nbsp;pay on the task I changed according to ME's spawn, you help me see, the problem is 2 points.
1, the red side captures the airport once after generating ground troops and anti-aircraft units. When captured by the blue side again after the capture of this airport will not automatically generate ground troops and anti-aircraft units.
2, I want to generate the specified troops in a specific area according to the flag markers generated after the capture of the airport on eithe





枫丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csofranz/DML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csofranz/DML] About rebirth after reaching the goal (Issue #3)





  
I want them to automatically generate air defense and ground troops infinitely according to the owner of the airfield
  
That should not be too difficult. If you are using Capturable Zones, the defenders only reproduce when they are destroyed, attackers produce regularly. If you are using FARP zones, I believe the default behavior is only once. Is that the issue that you are having (my apologies, but your descriptions are a bit too brief to fully understand what the issue may be :) )
 So, to establish what you are trying to do: You want an airfield or FARP that continually produces troops for the side that holds the airfield? You currently are using FARP Zone modules which only produce defenders once.
 You would prefer it if the FARP/Airfield continually produces ground forces but the FARP Zone doesn't do that.
 
Is that a correct assessment of what you are trying to accomplish and the issue you are facing?
 
If so, imagine the FARP/Airfield does automatically spawn defenders - when should that happen, and what should be spawned?
 
I think we'll find a way to make this work :)
